import Script from "next/script";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/reduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {
          typeof window !== "undefined" && (
            <Script
              src="https://telegram.org/js/telegram-web-app.js"
              strategy="beforeInteractive"
            />
          )
        }
      </head>
      <body
        className={`font-montserrat bg-[#F0E8E8]`}>
        <ReduxProvider>
          <Navbar />
          <div className="max-w-[1124px] mx-auto px-4">
            {children}
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
