import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/reduxProvider";
import ThemeProvider from "./themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      </head>
      <body
        className={`font-montserrat bg-[#F0E8E8] dark:bg-[#111111]`}>
        <ReduxProvider>
          <ThemeProvider>
            <Navbar />
            <div className="max-w-[1124px] mx-auto px-4">
              {children}
            </div>
            <Footer />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
